Dockerfile
poetry.lock
pyproject.toml
scripts/aws_helper.py
scripts/standardising.py
scripts/tests/aws_helper_test.py

Add the `standardising` script
- `standardising.py` has been added in the `script` directory
- Unit tests have been initialized
- some changes in `aws_helper` related to assuming a role

feat: add standardising script (TDE-303)

---

scripts/standardising.py

The standardising process should be run on multiple files (loop).
- Loop over a list of files and run the process for each file
> **_NOTE:_** TDE-411 needs to be included to make this change happenning.

feat: run standardising step on a list of files (TDE-412)

---

README.md
scripts/aws/aws_credential_source.py
scripts/aws/aws_helper.py
scripts/files/fs_s3.py
scripts/gdal/gdal_helper.py

- ci: cleanup ci pipeline
- feat: use role assumption helper to assume roles
- refactor: fixup lint/types

feat: automatically refresh role assumptions

---

scripts/gdal/gdal_preset.py
scripts/standardise_validate.py
scripts/standardising.py

Both are lossless compression for the top level imagery.
Webp is best suited for when there is RGB or RGBA imagery, LZW is best suited for any TIFF that is not Webp.

feat: switch between two gdal presets "lzw" or "webp"

---

scripts/initialise_stac_collection.py
scripts/stac/imagery/collection.py
scripts/stac/tests/collection_test.py
scripts/stac/util/STAC_VERSION.py

Feat: initialise collection stac TDE-453

---

scripts/collection_from_items.py
scripts/create_stac.py
scripts/standardise_validate.py

Along with https://github.com/linz/topo-workflows/pull/53

chore: rename cli arguments that were using underscore with a dash TDE-558

---

scripts/gdal/gdal_cutline.py
scripts/standardising.py

fixes
```
ImportError: cannot import name 'Geometry' from 'osgeo' (/usr/lib/python3/dist-packages/osgeo/__init__.py)
```

fix: correct type imports

---

scripts/standardising.py

fix: gdal info reference wrong file

---

scripts/files/file_tiff.py
scripts/files/tests/file_tiff_test.py
scripts/gdal/gdal_preset.py
scripts/standardising.py

[Example Output](https://basemaps.linz.govt.nz/?config=o215MBGedmy6nTiWwUgszffSJoTuGcsky3WTxPQ81qG4UCG47bAeC3Tx4Z9vZ8vfKWYGtSCJ1y7H2Fvbqk6GyRyK4U2zFKrizpfGRsdD5hDsnbUJXKMXZ2gpgfw3NUJ1F9MT1cvtaZYpyhgtCwQ6CVtmd6UTcYLGTNJjXvJ1Nmp2dE5WD7nmomoXnK7fAqJnzHqVL9u8JFS9etczhdhHbU9v1&i=test-chch&tileMatrix=NZTM2000Quad&debug#@-43.531450,172.631694,z9)
[Zoomed to 'Glitch' Example](https://basemaps.linz.govt.nz/?config=o215MBGedmy6nTiWwUgszffSJoTuGcsky3WTxPQ81qG4UCG47bAeC3Tx4Z9vZ8vfKWYGtSCJ1y7H2Fvbqk6GyRyK4U2zFKrizpfGRsdD5hDsnbUJXKMXZ2gpgfw3NUJ1F9MT1cvtaZYpyhgtCwQ6CVtmd6UTcYLGTNJjXvJ1Nmp2dE5WD7nmomoXnK7fAqJnzHqVL9u8JFS9etczhdhHbU9v1&i=test-chch&p=NZTM2000Quad&debug=true#@-43.5394150,172.6123336,z17.3381) - see https://toitutewhenua.atlassian.net/browse/BM-772

Feat: convert nodata to alpha TDE-625

---

scripts/collection_from_items.py
scripts/stac/imagery/collection.py
scripts/stac/imagery/provider.py
scripts/stac/tests/collection_test.py

Add STAC `providers` in the `collection.json`. (https://github.com/radiantearth/stac-spec/blob/fd8fb4e3cf0b6c4a0fe74822accbc1725a92f92a/collection-spec/json-schema/collection.json#L71)
:warning: https://github.com/linz/topo-workflows/pull/97 to handle the two new arguments `--producer` and `--licensor` + a list of providers.
- `name` and `roles` attributes only
- no duplication check (on `name` or `role`) - only for `Toitū Te Whenua Land Information New Zealand` when added at the `collection` object construction. **That is something that would need to be taken into account if a company can be both `producer` and `licensor`.**
- no control on the `provider` name passed. They will be defined and not modifiable in the `standardising` Argo Workflows `WorkflowTemplate`
```
{"type": …
```

feat!: stac providers TDE-623

---

scripts/files/file_tiff.py

This will ensure other nodata values will also get converted to alpha such as 0

fix: remove no data value (255)

---

.github/workflows/containers.yml

https://github.com/aws-actions/configure-aws-credentials#usage

fix: add permissions

---

.github/workflows/containers.yml

fixing mistake, should be tagged as latest

fix: add latest to tag

---

scripts/tile/tile_index.py

Update `docstring` and few comments for `tile_index.py` script, mostly copied over from https://github.com/linz/argo-tasks/pull/422 for better understanding and consistency

docs: update docstring for tile_index.py

---

scripts/files/file_tiff.py
scripts/files/tests/file_tiff_test.py
scripts/gdal/gdal_bands.py
scripts/gdal/gdal_preset.py
scripts/gdal/tests/gdal_bands_test.py
scripts/gdal/tests/gdal_preset_test.py
scripts/standardising.py

LERC GDAL Command: `gdal_translate -q -of COG -co blocksize=512 -co num_threads=all_cpus -co sparse_ok=true -co bigtiff=yes -a_srs EPSG:2193 -stats -co compress=lerc -co max_z_error=0.001`
Example Processed Tiff:
[CF15_1000_3748.zip](https://github.com/linz/topo-imagery/files/11888193/CF15_1000_3748.zip)

feat: add dem_lerc  preset TDE-779

---

.github/dependabot.yml

Important to enable automated updates of dependencies once pinning <https://github.com/linz/topo-imagery/pull/744> is merged.

feat: Dependabot for Docker TDE-963

---

scripts/aws/aws_helper.py
scripts/files/files_helper.py
scripts/files/fs.py
scripts/files/fs_s3.py
scripts/files/tests/file_helper_test.py
scripts/files/tests/file_tiff_test.py
scripts/files/tests/fs_s3_test.py
scripts/gdal/gdal_bands.py
scripts/gdal/gdal_preset.py
scripts/gdal/tests/gdal_bands_test.py
scripts/standardising.py
scripts/thumbnails.py

Consistency and PEP-8 compliance.
Found some issues with IDEA.
None of these are applicable.

refactor: PEP-8 compliance

---

scripts/stac/tests/collection_test.py

Test about Collection providers were not explicit enough.
Comment the test to give explaination about what the test does.

docs: add explanation about collection provider tests

---

scripts/collection_from_items.py

fix a typo that causes errors
This change fixes a typo.
This highlights a missed test. I will created one but this fix should be merged ASAP so production can continue. 
~~- [ ] Docs updated~~
~~- [ ] Issue linked in Title~~

fix: typo in prod

---

.pre-commit-config.yaml
.pylintrc

Don't run the duplicate code test.
We might end up with lots of duplication, especially in the tests. This is a code smell, but not necessarily a deal breaker.
N/A

fix: Disable duplicate code test

---

scripts/stac/imagery/capture_area.py

I want to know when starts and how long takes this process
Add some logs

feat: log capture-area generation duration TDE-1080

---

scripts/files/file_tiff.py
scripts/gdal/gdal_preset.py

Ensure that the "magic" value is justified.
Refer back to the document which specifies the value.

docs: Document default "no data" value TDE-1077

---

scripts/files/tests/fs_s3_test.py
scripts/files/tests/fs_test.py
scripts/stac/imagery/tests/collection_test.py
scripts/stac/imagery/tests/item_test.py

Fix repo and make it easier to work with.
Also annotate all ignored types.

fix: Make compatible with latest moto

---

scripts/files/fs_s3.py

Improve IDE type hinting.
Use type definitions from separate package only at type checking time.

fix: Use correct types for S3 client TDE-1147

---

scripts/files/tests/conftest.py
scripts/files/tests/fs_local_test.py
scripts/stac/imagery/item.py
scripts/tests/datetimes_test.py

Verify that our code handles arbitrary datetimes, and not just specific ones. Also clarify tests with which parts of the inputs are arbitrary, and which ones tie strictly to the assertions.
Create a function to return a random epoch datetime.

refactor: Pull out function for any epoch datetime TDE-1147

---

.github/pull_request_template.md

Update the Pull Request template to a simpler newer one (using [the template from the Argo Workflows GitHub Repository](https://github.com/argoproj/argo-workflows/blob/main/.github/pull_request_template.md)).
Update the PR template.

feat: use new pull request template

---

scripts/files/file_tiff.py
scripts/files/tests/file_tiff_test.py
scripts/gdal/gdal_bands.py
scripts/gdal/gdal_preset.py
scripts/gdal/gdal_presets.py
scripts/gdal/tests/gdal_bands_test.py
scripts/gdal/tests/gdal_preset_test.py

Reduce the amount of magic strings in the code base
None.

refactor: Pull out enum for presets

---

scripts/gdal/gdal_helper.py
scripts/gdal/gdal_preset.py
scripts/gdal/tests/gdal_preset_test.py
scripts/standardising.py

refactor: Use numeric enum for EPSG codes

---

scripts/gdal/gdal_helper.py
scripts/gdal/tests/gdal_preset_test.py
scripts/standardising.py

https://github.com/linz/topo-imagery/pull/1061/files#r1751185243
None.

refactor: Clarify enum entry names

---

scripts/stac/imagery/create_stac.py
scripts/stac/imagery/tests/create_stac_test.py
scripts/standardise_validate.py

Test was incorrect.
- update test
- init start_datetime and end_datetime if derived_from
run pytest and a local test

fix: start_datetime and end_datetime must be init if derived_from TDE-1258

---

scripts/standardise_validate.py

Simplify code for maintainability purposes
N/A

refactor: Simplify standardise_validate.py TDE-1270

---

pyproject.toml

The project authors should be up-to-date.
Keep a relevant list of authors.

build: update authors

---

scripts/gdal/gdal_presets.py

The link to the cog-quality documentation is broken. The documentation has moved somewhere else.
Link to the correct location of the documentation

docs: update cog-quality link

---

scripts/stac/imagery/collection.py

This docstring refers args that are incorrect.
Remove incorrect arg

docs: cleanup collection.update() docstring
