linz/topo-imagery

.github/workflows/build.yml
.github/workflows/containers.yml

Add a build pipeline containing the steps to build and publish the gdal docker image on each push related to changes in the `containers` folder on the master branch.
The image will be published in the GitHub LINZ Packages repository under the name `topo-imagery-gdal`.

ci: init build.yml with build and publish container steps

---

scripts/create_polygons.py

The `create_polygons.py` script was writting the destination file at the root of the `destination` bucket.
`destination` can be a full s3 path and the destination file will be written in this path.

feat: create_polygons destination can be a full s3 path

---

.dockerignore
Dockerfile

Everytime a script is added in the `/scripts/` directory, we should not have to specify it in the `Dockerfile`
- Add a `.dockerignore` file to exclude the tests and cache
- Modify the `Dockerfile` to include all the scripts (path instead of each file)
> **_NOTE:_**  If a script needs to be excluded, use the `.dockerignore` file.

chore: include all scripts in COPY in the Dockerfile (TDE-415)

---

Dockerfile
scripts/aws_helper.py
scripts/file_helper.py
scripts/gdal_helper.py
scripts/non_visual_qa.py
scripts/standardising.py
scripts/tests/non_visual_qa_test.py

Cloudify the [non visual QA script](https://github.com/linz/aerial-imagery-scripts/blob/master/non_visual_qa/non_visual_QA.py)
- explore ways of providing/displaying the output - current ouput in logs:
```
[2022-07-07T04:58:27.074Z] INFO non_visual_qa_result result={ 0=noDataValue not set 1=not 3 bands, 4 bands found 2=different srs 3=unexpected color interpretation bands; band 4 Undefined 4=b'Warning 1: The definition of projected CRS EPSG:2193 got from GeoTIFF keys is not the same as the one from the EPSG registry, which may cause issues during reprojection operations. Set GTIFF_SRS_SOURCE configuration option to EPSG to use official parameters (overriding the ones from GeoTIFF keys), or to GEOKEYS to use custom values from GeoTIFF keys and drop the EPSG code.\n' }

feat: Non Visual QA script (TDE-309)

---

README.md
scripts/gdal_helper.py
scripts/standardising.py

the destination arguement has been removed therefore the output of standardardisation will only be written to the tmp directory in the docker container. combined with https://github.com/linz/topo-workflows/pull/7 the tmp folder will then be written to the artifacts bucket. 
note: this branch includes COG work, it needs to be rebased once https://github.com/linz/topo-imagery/pull/60 is merged

Feat: tde-421 remove destination arguments

---

scripts/standardising.py

The temporary files generated with `gdal` should not been deleted as we need to push them to the Argo artifact bucket at the end of the workflow.
- Not using a `TempDir` which is empty at the end of the process, but write the files in the `/tmp/` folder which is passed to Argo as Artifact output.
FYI, I've submitted the following workflow in order to test the change:
```
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
generateName: imagery-standardise-
spec:
serviceAccountName: workflow-runner-sa
podGC:
strategy: OnPodCompletion # Delete pod once its finished
nodeSelector:
karpenter.sh/capacity-type: "spot"
entrypoint: main
arguments:
parameters:
- name: uri
value: "s3://linz-imagery-staging/RGB/nelson/2022/06/nelson-urban/"
- name: filter
value: "2022_BQ27_1000_2001.tif" …
```

fix: keep temporary files so they are pushed to the artifact bucket

---

scripts/gdal_helper.py
scripts/non_visual_qa.py
scripts/tests/non_visual_qa_test.py

In order to facilitate the loggin in Elastic Search, the Non Visual QA error report should be in a JSON format.
- Create a `dictionnary`
```json
{"file": "path/to/the/file", "errors": [{"type": "error_type", "message": "error_message"}]}
```
```json
{"file": "s3://linz-imagery-staging/RGBi4/tasman_rural_2020_0.3m_a_RGBI/tif/2020_BQ24_5000_0601.tif", "errors": [{"type": "gdalinfo", "message": "error(s): b'Warning 1: The definition of projected CRS EPSG:2193 got from GeoTIFF keys is not the same as the one from the EPSG registry, which may cause issues during reprojection operations. Set GTIFF_SRS_SOURCE configuration option to EPSG to use official parameters (overriding the ones from GeoTIFF keys), or to GEOKEYS to use custom values from GeoTIFF keys and drop the EPSG code.\\n'"}, {"type": …
```

fix: log Non Visual QA error report in a JSON format

---

scripts/cli_helper.py
scripts/create_polygons.py
scripts/non_visual_qa.py
scripts/standardising.py
scripts/tests/cli_helper_test.py

Parsing the `--source` argument code was duplicated in every scripts. Also `pylint` was complaining.
- Create a single method which parse the argument `--source` and return a list of path (using `format_source` #36)

refactor: common source parser

---

poetry.lock
pyproject.toml

This is a temporary solution to fix the build that fails on `poetry install` because of a dependency issue. See https://github.com/python-poetry/poetry/issues/5977 & https://github.com/python-poetry/poetry/issues/1889

fix: add 'certifi' lib to temporary fix poetry install issue TDE-451

---

scripts/files/files_helper.py
scripts/standardising.py

So that we can get the stac item id from the filename

fix: TDE-454 remove `standardise` from file name

---

scripts/aws/aws_helper.py
scripts/gdal/gdal_helper.py

- fix: retry upto 3 times when InvalidIdentityTokenException happens
- fix: retry fetching credentials on failure

fix: retry upto 3 times when InvalidIdentityTokenException happens

---

scripts/aws/aws_helper.py

```
File "/app/scripts/aws/aws_helper.py", line 103, in get_session_credentials
credentials: AwsFrozenCredentials = get_session(prefix).get_frozen_credentials()
AttributeError: 'Session' object has no attribute 'get_frozen_credentials'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/app/scripts/non_visual_qa.py", line 161, in <module>
main()
File "/app/scripts/non_visual_qa.py", line 157, in main
non_visual_qa(source)
File "/app/scripts/non_visual_qa.py", line 145, in non_visual_qa
file_check.run()
File "/app/scripts/non_visual_qa.py", line 99, in run
gdalinfo_process = run_gdal(gdalinfo_command, self.path)
File "/app/scripts/gdal/gdal_helper.py", line 63, in run_gdal
credentials = get_session_credentials(input_file)
File …
```

fix: a couple of bugs in get_session_credentials

---

scripts/files/file_check.py
scripts/gdal/gdalinfo.py
scripts/non_visual_qa.py
scripts/standardise_validate.py
scripts/tests/non_visual_qa_test.py

1
Code still runs as usual, should see no changes needed in topo workflows other than updating the version number. 
refactored to have gdalinfo in one location some changes have been done (splitting functions) in preparation to add stac item creation to standardise_validate.py
to run:
`docker run -v ${HOME}/.aws/credentials:/root/.aws/credentials:ro -e AWS_PROFILE=**profile** **container**:latest python standardise_validate.py --preset "webp" --source "[\"**s3://lpath/to.tif**\", \"**s3://path/to.tif**\"]"`

refactor: single location for gdalinfo, refactor standardise_validate.py TDE-483

---

scripts/collection_from_items.py
scripts/create_stac.py
scripts/files/fs_s3.py
scripts/stac/imagery/collection.py
scripts/stac/tests/collection_test.py
scripts/standardise_validate.py

| arg             | desc                   | user input required?                 |
|-----------------|------------------------|-----------------------------|
| --uri           | path to items & write location of collection.json          | no, s3://..../flat/         |
| --collection_id | ulid                   | no, output of generate_ulid |
| --title         | collection title       | yes                         |
| --description   | collection description | yes                         |
note: there is currently no validation of `--title`, in future, this may need to be added if the title is going to be used to determine the publish path.

feat: create collection TDE-453

---

Dockerfile

We are using an unstable version of the `osgeo/gdal` Docker container by using the `latest` tag. Using `latest` is problematic as the version can change when the container is re-build. We currently can't use a stable version as we would have to downgrade from a `gdal-3.6-dev` version with Python `3.10` to `gdal-3.5.3` with Python `3.8.10` leading to some Poetry/pip/Python issues (from few tests that we've done).
Fixed the `osgeo/gdal` container version to `osgeo/gdal@sha256:452da485c574fe040a5748b73932d3ec7334913197744b550d13ce80493ef3c4` until a `gdal-3.6` stable container is released so we can use it.

feat: use a fixed version of osgeo/gdal container TDE-555

---

scripts/gdal/gdal_helper.py
scripts/gdal/gdalinfo.py

`stderr` from `gdal` should not be interpreted as an error. When `gdal` is on error, it returns an `exit code` <> 0. This behaviour is already captured by `subprocess.run` (with `check=True`) raising a `subprocess.CalledProcessError` in a case of _"a non-zero exit status"_. Any `stderr` should be `Warnings` or other messages <> error.
Log a warning instead of raising an exception when `gdal` `stderr` is not empty

fix: log gdal stderr instead of raising an exception TDE-557

---

scripts/gdal/gdal_helper.py
scripts/standardising.py

Assuming that our container has the same GDAL version for the different command we run, logging the result of `gdalinfo --version` to get the GDAL version we use in our logs.

feat: log the gdal version when run standardising TDE-559

---

.github/workflows/format.yml
Dockerfile
poetry.lock
pyproject.toml

We were using a non stable (`dev`) version of GDAL 3.6. Now `osgeo` released a stable version of their containers, we should use it instead.

feat: upgrade to stable GDAL v3.6 TDE-565

---

scripts/collection_from_items.py
scripts/create_stac.py
scripts/files/fs_s3.py
scripts/stac/tests/collection_test.py

(also includes: deletion of unused code in `create_stac.py` and a refactor of `collection_test.py`)
tested on: `s3://linz-workflow-artifacts/2022-11/03-imagery-standardising-v0.2.0-49-s46rd/flat/`
processes 2569 items in ~34449.404296875ms (a significant improvement!)
if you want, it is very satisfying to test in docker:
Comment out line 60 in collection_from_items.py and run on flat folder that doesn't have a collection, for example:
```
docker run -v ${HOME}/.aws/credentials:/root/.aws/credentials:ro -e AWS_PROFILE=li-topo-prod topo-imagery:latest python collection_from_items.py --uri s3://linz-workflow-artifacts/2022-11/03-imagery-standardising-v0.2.0-49-s46rd/flat/ --collection-id 01GGXEJG2YEM7SM6CC7KSWFM0S --title temp_title --description temp_description --concurrency 25 | pjl
```

refactor: improve processing time of collection creation TDE-258

---

scripts/files/geotiff.py
scripts/stac/imagery/item.py
scripts/stac/tests/item_test.py

The bbox and geometry were coerced into the existing code when TDE-502 was done, this is to tidy that up.

fix: tidy up geometry and bbox TDE-522

---

Dockerfile

Increments the osgeo/gdal container version from `3.6.0` to `3.6.1`.
Version 3.6.1 is nominally a bug fix release, but includes changes made in [GDAL pull request 6907](https://github.com/OSGeo/gdal/pull/6907) to improve the performance of gdalwarp when supplying a cutline, as raised by @blacha in [GDAL issue 6905](https://github.com/OSGeo/gdal/issues/6905).

chore: update osgeo/gdal container to 3.6.1

---

.github/workflows/containers.yml
.github/workflows/release-please.yml

Use `--all-tags` flag in order to avoid falling into a rate limit by pushing multiple tags in sequence
Same change for `argo-tasks` https://github.com/linz/argo-tasks/pull/214

ci: use docker push --all-tags to avoid multiple push TDE-626

---

scripts/standardise_validate.py

The `vsis3` path were wrong for both `standardised_path` and `original_path`

fix: log wrong vsis3 path non visual qa TDE-563

---

scripts/cli/cli_helper.py
scripts/cli/tests/cli_helper_test.py
scripts/collection_from_items.py

Data Managers need to add several `licensors` in some rare cases. 
- `collection_from_items.py` takes a new optional argument `--licensor-list` and expect a string representing a list separated by semicolon `;` (example: `Waka Kotahi; Nelson City Council; Tasman District Council`). This argument is used if there is more than 1 element in the list. Otherwise, `--licensor` is used.
- quick refactor moving `/scripts/test/` to `/scripts/cli/tests` as it was related to `/cli` only.
https://argo.linzaccess.com/workflows/argo/test-imagery-standardising-multilicensors-wxvt7?tab=workflow&nodeId=test-imagery-standardising-multilicensors-wxvt7-3822207485
`"providers": [{"name": "Auckland", "roles": ["licensor"]}, {"name": "Nelson Council", "roles": ["licensor"]}, {"name": "LINZ", "roles": …

feat: add multiple STAC licensors TDE-643

---

scripts/files/file_tiff.py
scripts/standardise_validate.py

Allow to pass `--scale` with `"None"` to skip the tile check

feat: make scale optional

---

poetry.lock
pyproject.toml

Project seems to build fine after removing https://github.com/linz/topo-imagery/pull/88 workaround

chore: remove certifi which was added as workaround

---

.github/workflows/containers.yml
.github/workflows/release-please.yml
README.md

Follows the guidelines here: https://github.com/aws-actions/amazon-ecr-login#building-and-pushing-an-image
**Cost:** https://aws.amazon.com/ecr/pricing/
In particular - storage: $0.10 per GB /Month
**Lifecylce:** https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html
Branch: `test/aws-configure`
First Deployment:
Second Deployment (after update to topo-imagery):

feat: deploy containers to ecr TDE-689

---

.github/workflows/containers.yml
.github/workflows/release-please.yml

publishing to Github CR requires:
https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#publishing-a-package-using-an-action
```
permissions:
contents: read
packages: write
```
configuring aws credentials requires:
https://github.com/aws-actions/configure-aws-credentials#usage
```
permissions:
id-token: write
contents: read
```

fix: update permissions

---

.github/workflows/containers.yml
.github/workflows/release-please.yml

this tidies the workflow, removes the need for a secret and makes the workflow easier to copy between repos

ci: use env vars TDE-704

---

Dockerfile
scripts/gdal/gdal_preset.py

- GDAL is not publishing on `docker.io` anymore
- Remove workaround for https://github.com/OSGeo/gdal/issues/7478 since it's included in `3.7.0`

chore: upgrade gdal from 3.6.1 to 3.7.0

---

scripts/cli/cli_helper.py
scripts/cli/tests/cli_helper_test.py
scripts/collection_from_items.py

Adds `--producer-list` argument to `collection_from_items.py` to allow passing multiple producers to the STAC metadata.
There is a slight change to how both `--licensor-list` and `--producer-list` are handled, which resolves what I think is an edge case that is currently not handled.
Currently, if `--licensor-list` is passed a value without `;`, and `--licensor` is not passed, the output STAC file will include `{ "name": null, "roles": ["licensor"] }`. This PR fixes that, so that it will just not be present in the output.
Alternatively, it could be included as a single un-split item by removing the `and ";" in arguments.licensor_list` checks.
*Edit:* Which now that I've looked at where it's used in the standardising workflow I see would never eventuate in practice, as `--licensor` gets a …

feat: add --producer-list to allow multiple producers TDE-781

---

scripts/collection_from_items.py

If the `collection_from_items.py` is run with a `--uri` source of an S3 path which already contains a `collection.json` file which is the output of a previous run of the script, it will fail.
This is because of a KeyError exception for `"collection"`, which all the item STAC files have, but which the resulting `collection.json` file does not, as the collection ID is instead stored in the `"id"` key.
Swapping from `item_stac["collection"]` to `item_stac.get("collection")` eliminates this KeyError exception, and allows the script to run happily with a previously existing `collection.json` file, as it will be skipped and then overwritten.

fix: handle already existing collection.json

---

scripts/gdal/gdal_bands.py
scripts/gdal/gdalinfo.py
scripts/gdal/tests/gdal_bands_test.py
scripts/gdal/tests/gdalinfo.py

These changes handle TIFFs with a band of Palette colour interpretation type, using the [-expand](https://gdal.org/programs/gdal_translate.html#cmdoption-gdal_translate-expand) argument to gdal_translate. This takes the contents of the colour palette and applies it to the rgb/rgba bands in the output file.
This resolves the following error encountered when standardising historical imagery survey SN9911:
ERROR 6: GTIFFBuildOverviews() doesn't support building overviews of multiple colormapped bands.
which used the band arguements -b 1 -b 1 -b 1.
This PR supersedes https://github.com/linz/topo-imagery/pull/310 which was proposed when previously processing historical imagery. I've made a new PR mainly to simplify having to rebase 6 months worth of changes from master onto that branch. …

feat: handle standardising paletted tiffs

---

Dockerfile
scripts/gdal/gdal_preset.py

This reverts commit 810b73c566e482b3caf29a73c1ffaccc32a6a1b4. 
We don't need to revert the previous commit anymore.

revert: "revert: "chore: upgrade gdal from 3.6.1 to 3.7.0"" TDE-810

---

.github/workflows/containers.yml
.github/workflows/release-please.yml

This PR is following the same change that has been made in https://github.com/linz/argo-tasks/pull/544
Additionnaly manage not pushing container on AWS if credentials are not present (using a fork for example). This additional change will be added to `linz/argo-tasks` in a future PR.

ci: refactor container publishing and use Docker metadata

---

scripts/gdal/gdal_preset.py

This is to fix the `gdalbuildvrt does not support heterogenous projection` error when the coordinate system description is different (for tiffs having the same EPSG). This also allows to build a VRT file with tiffs having different EPSG, which is not what we want. However, in our workflow, the `argo-task` `tile-index-validate` verify that all the images have the same EPSG code.
I've been testing this fix retiling `DEM_BA32_2016_1000_4032.tif` and `DEM_BA32_2016_1000_4031.tif` which was failing without this fix.
I could not generate a test case from the production case having this issue we had. The process to create a lighter tiff does modify this coordinate system description removing the slight difference that was present before generating "smaller" tiffs.

fix: gdalbuildvrt fails when different coordinate system desc TDE-818

---

scripts/files/files_helper.py
scripts/files/fs.py
scripts/files/fs_s3.py
scripts/files/tests/fs_s3_test.py
scripts/stac/imagery/collection.py
scripts/standardise_validate.py
scripts/standardising.py
scripts/thumbnails.py

Allows `fs_s3.write()` to specify a content type to the object pushed into a S3 bucket.
TIFF:
``` bash
aws s3api head-object --bucket linz-workflow-artifacts --key 2023-09/05-test-imagery-standardising-paul-84xsp/flat/BX24_5000_0405.tiff
{
"AcceptRanges": "bytes",
"Expiration": "expiry-date=\"Tue, 05 Dec 2023 00:00:00 GMT\", rule-id=\"OWVkZjBkNWMtZDIwNC00ZjI3LWEzOTUtODU0ZGJiYmFkZmFm\"",
"LastModified": "2023-09-05T23:40:49+00:00",
"ContentLength": 1725950,
"ETag": "\"9c6af70db952ceef70ea6d5a0651abf9\"",
"ContentType": "image/tiff; application=geotiff; profile=cloud-optimized",
"ServerSideEncryption": "AES256",
"Metadata": {}
}
```
JSON:
``` bash
aws s3api head-object --bucket linz-workflow-artifacts --key 2023-09/05-test-imagery-standardising-paul-84xsp/flat/BX24_5000_0405.json
{ …
```

feat: provide content type to S3 objects TDE-859

---

.github/workflows/format-tests.yml
scripts/standardising.py
scripts/tests/data/restandardise.json

For a 1:1 (non-retile) re-standardise of already processed imagery, the input filepath was the same as the output filepath.

fix: re-standardising TileByteCounts error TDE-850

---

scripts/gdal/gdal_preset.py
scripts/gdal/tests/gdal_preset_test.py

When standardising a COG with overviews, the existing webp overviews were used to create the overviews with further lossy compression.
This change forces creation of overviews from the base image.

fix: recreate webp overviews TDE-869

---

Dockerfile

There has been a high rated CVE for webp that was fixed in a re-release of GDAL 3.7.2 
ref: https://github.com/OSGeo/gdal/issues/8501

fix: upgrade gdal to 3.7.2 for webp CVE fix TDE-897

---

.github/workflows/containers.yml
.github/workflows/release-please.yml

**motivation**
New ecr repositories have been created (https://github.com/linz/topo-aws-infrastructure/pull/206) and we need to deploy our containers to these new locations
**modification**
changed actions to push containers to new repositories.
For example: topo-imagery/latest rather than eks/topo-imagery-latest

feat: re-point ci to topo-imagery ecr repository

---

.github/workflows/containers.yml
.github/workflows/format-tests.yml
.github/workflows/release-please.yml

Done with pin-github-action <https://github.com/mheap/pin-github-action> 1.8.0 using `npx pin-github-action .github/workflows/*.yml`.
Dependabot should support updating in the same fashion <https://github.com/dependabot/dependabot-core/issues/8277#issuecomment-1782819752>.
Had to `export GH_ADMIN_TOKEN=github_pat_…` using a fine-grained personal access tokens with no extra access to work around rate limiting *and* to be able to work in private repos
<https://github.com/mheap/pin-github-action/issues/73>.

feat: Pin actions to hashes TDE-934

---

scripts/stac/imagery/collection.py
scripts/stac/tests/generate_title_test.py

The dataset titles and descriptions should be consistent with current datasets. 
- remove spaces between years `(2022 - 2023)` -> `(2022-2023)`
- Capitalise preview `- preview` -> `- Preview`
nb: should be merged and release ASAP to avoid inconsistencies

fix: minor changes to be consistent with current data TDE-955

---

scripts/collection_from_items.py

Being able to still use the human readable name for the categories have been kept in order to avoid a breaking change. Meanwhile, another breaking change has been pushed resulting in a new major version of `topo-imagery`. This workaround to avoid breaking change does not need to exist anymore.
Remove the possibility of using human readable names for the `--category` argument.

feat: accept only hyphen named categories TDE-985

---

scripts/files/fs.py
scripts/files/tests/fs_test.py

Downloading sidecar files process currently stop as soon as one of them does not exist, without looking for the others.
Catch and add the `NoSuchFileError` to the `Future` exception and look for the exceptions once the downloading process (of all sidecar files) is completed, rather than stopping it as soon as one exception is raised.

fix: NoSuchFileError is stopping multiprocessing sidecar files TDE-1007

---

.github/workflows/format-tests.yml
scripts/files/fs.py
scripts/files/tests/fs_test.py

`write_file()` was not handling exception correctly due to calling another function in the `executor` arguments.
- Create a `copy()` method (calling `write()` and `read()`) that allow the `executor` to call a single function.
- Refactor/simplify some code for readibility

fix: write_file was not handling exception correctly TDE-1007

---

.github/workflows/format-tests.yml

A PR made from a fork should be able to run the `format-tests` workflow.
Allow the `format-tests` workflow to be run from any PR aiming to be merged to the master branch.

ci: allow fork PR to run format-test gh action TDE-1032

---

scripts/stac/imagery/collection.py
scripts/stac/imagery/metadata_constants.py
scripts/stac/tests/collection_test.py
scripts/stac/tests/generate_description_test.py
scripts/stac/tests/generate_title_test.py

refactor title & description formatting to align with naming documentation
- docstring updated to point to `naming.md`
- `event` removed from all titles as should now also be included in `geographic_description`
- `geographic_description` removed from elevation description otherwise, if the dataset has an event it will be repeated
Examples:
`Hawke's Bay Cyclone Gabrielle 0.3m Rural Aerial Photos (2023)`
`Ponsonby 0.3m Rural Aerial Photos (2023)`
`Hawke's Bay Cyclone Gabrielle 0.3m Satellite Imagery (2023)`
`Auckland LiDAR 0.3m DSM (2023) - Preview`

refactor: title & description TDE-955

---

scripts/files/file_tiff.py
scripts/standardising.py

After standardising a TIFF, a `gdalinfo` is run in order to [validate the file](https://github.com/linz/topo-imagery/blob/94051b83f76c9983996e52cf1ca4fb3118c82716/scripts/standardise_validate.py#L76).
When the `target` is on S3, this `gdalinfo` is run on the file stored in S3. This is not ideal (network performance) especially when the system has direct access to the local TIFF before being written to the cloud storage.
- Allow to run `gdalinfo` for the `FileTiff` object from a different path than the final path
- Force the `FileTiff` `gdalinfo` to be run from the local path and saved for future usage

refactor: save local standardised file gdalinfo in FileTiff object TDE-929

---

scripts/files/file_tiff.py
scripts/files/files_helper.py
scripts/files/tests/file_helper_test.py
scripts/gdal/gdal_bands.py
scripts/gdal/gdal_helper.py
scripts/gdal/gdalinfo.py
scripts/stac/imagery/create_stac.py
scripts/standardising.py
scripts/thumbnails.py

Helping running `gdal`commands should be done by `gdal_helper.py`. 
Move helper methods that run `gdal` to `gdal_helper.py`.

refactor: reorganise gdal helper

---

.github/workflows/format-tests.yml
scripts/cli/cli_helper.py
scripts/files/file_tiff.py
scripts/files/files_helper.py
scripts/files/fs_s3.py

Some of the `docstring` comments contain `doctest`. Some were wrong. `doctest` are useful to have a quick understanding of what is doing a method based on an example, rather than navigate to test files (if there is any). Having them right is even better.
Allow `pytest` to run the `doctest` by adding the `--doctest-modules` flag.

ci: add doctest check

---

scripts/gdal/gdal_helper.py

When running `gdal` with a file located on AWS S3, the system always try to request credentials from the `bucket-config` in order to access the file. In the case of the credentials are not needed, the system should not request them and read the file.
Downloading the file in a temporary directory and running gdal against this local file. Tt can use the existing logic of reading a file on S3 which first try to read it before requesting credentials.

fix: gdal should try reading before getting credentials TDE-929

---

scripts/stac/imagery/collection.py
scripts/stac/imagery/tests/collection_test.py

In order to allow Argo Workflows UI to expose a file to the user, the file has to be stored in the local machine. The workflows can then pulled the file as an artifact output. https://github.com/linz/topo-workflows/pull/443
Save a copy of  `capture-area.geojson` file in a different path than the one linked to the STAC Collection.
Another option would be to only save the file locally and let Argo Workflow to save it to the target directory. I haven't choose that option to monitor AWS issues from the application rather than from Argo.

feat: save a copy of capture-area.geojson as an artifact for Argo Workflows TDE-1045

---

scripts/gdal/gdal_preset.py
scripts/gdal/tests/gdal_preset_test.py

Existing overviews were only being ignored when webp overview compression was used. This was not used by the dem_lerc preset so overviews were not being ignored for LERC compressed DEMs/DSMs and therefore when restandardising already standardised datasets the quality of the overviews could be degraded.
Move the `overviews=ignore_existing` `gdal_translate` configuration option to the `BASE_COG` configuration so it is always set.

fix: always ignore existing overviews TDE-1046

---

scripts/stac/imagery/capture_area.py
scripts/stac/imagery/tests/capture_area_test.py
scripts/stac/imagery/tests/collection_test.py
scripts/standardising.py

The default behaviour of `gdal_footprint` is to set a maximum limit of 100 points in each footprint. This is not enough for all tiles, resulting in some gaps between tiles and not enough detail on more complicated shapes. The solution is to allow unlimited points in tile footprints, and to increase the buffer distance used when simplifying the capture area.
A buffer size of 2 * gsd was chosen after some investigation, [recorded in TDE-1049](https://toitutewhenua.atlassian.net/browse/TDE-1049). The aim is to reduce the number of vertices and therefore the file size, while still describing the capture area in enough detail.
- `gdal_footprint` use the `-max_points unlimited` option
- Set the capture area to use 2 * gsd for the buffer distance.

fix: don't limit footprint points, increase capture area buffer TDE-1049

---

scripts/stac/imagery/collection.py
scripts/stac/imagery/tests/generate_description_test.py

Slight change to the wording of the STAC collection description for DEMs and DSMs for readability and consistency.
Add in the word "captured" for dem/dsm data type stac collection description.

fix: update dem/dsm STAC collection description wording TDE-955

---

scripts/stac/imagery/collection.py
scripts/stac/imagery/tests/generate_description_test.py

A release please release.
Because the previous commit had a "test" prefix that did not trigger a release.

fix: update wording for release

---

scripts/files/file_tiff.py
scripts/standardise_validate.py
scripts/standardising.py

Path are converted to URL in argo-tasks which can percent-encode (example, space to `%20`).
Quick fix that unquotes percent-encoded sequences in input paths.
Long term fix could be using URL in this repo?

fix: handle percent-encoded urls TDE-1054

---

.github/workflows/format-tests.yml
README.md
scripts/stac/imagery/capture_area.py
scripts/stac/imagery/collection.py
scripts/standardise_validate.py
scripts/standardising.py

Since [ `max_points unlimited` has been introduced in the `gdal_footprint`](https://github.com/linz/topo-imagery/pull/872) call, generating the capture-area might take a very long time due to the complexity of the single footprint polygon that are merged.
Simplify single footprint geometry using the same buffer distance its used for the capture-area geometry.
From one test standardising [Canterbury - Banks Peninsula LiDAR 1m DEM (2023)](https://github.com/linz/elevation/blob/master/stac/canterbury/banks-peninsula_2023/dem_1m/2193/collection.json) dataset, the create-collection step running time:
- without simplifying footprints: 2m46s
- simplifying footprints: 12s

feat: simplify footprint geometry tde-1080

---

scripts/standardising.py

The standardising process for a single tile is skipped if the output TIFF already exists in the target. However, the footprint file could not exists in the target directory if the system has stopped before writing the footprint to the target.
Quick solution of writing the footprint file before the output TIFF to make sure the footprint exists if the TIFF exists.

fix: footprint should exists if tiff already exists

---

scripts/files/file_tiff.py
scripts/files/tests/file_tiff_test.py
scripts/gdal/gdal_helper.py
scripts/gdal/tests/gdalinfo.py

It's represented as a decimal number string in the `gdalinfo -json`
output, so we should treat it as such in the code. This should detect
any values not numerically equal to -9999.

fix: Treat "no data" value as a decimal number TDE-1077

---

scripts/stac/imagery/tests/collection_test.py

Simplifies the test.
Also handle the `shapely.simplify` results from geos 3.12.

fix: Use integer coordinates TDE-1077

---

scripts/stac/imagery/tests/collection_test.py

The integer coordinates were easier to debug with, but also represented an unrealistically large area.
This partially reverts commit b381bb690d7bef68d15194b147568bcd1b8561f1.

test: Use original coordinates TDE-1077

---

scripts/gdal/gdal_helper.py
scripts/standardise_validate.py

The `vsis3` path is logged in order to facilitate the user to investigate an issue on the output tile by running gdal directly with the path copied from logs.
The path is currently logged wrongly: when the script is ran on Argo Workflows, the standardised path is already a S3 path (as target is S3 scratch bucket).
The result with the old implementation gave a path like `/vsis3/linz-workflows-scratch/2024-02/14-test-northland-2018-2020-dsm-1mtfvvz/test-northland-2018-2020-dsm-1mtfvvz-standardise-validate-1780775412/s3:/linz-workflows-scratch/2024-02/14-test-northland-2018-2020-dsm-1mtfvvz/flat/AX27_10000_0105.tiff`
Change the implementation to use `get_vfs_path` which replaces `s3://` by `/vsis3/`.

fix: wrong vsis3 path logged

---

Dockerfile

Update GDAL to 3.8.4 for bug fixes, specifically footprints bug TDE-1106.
Update to 3.8.4 in Dockerfile.

fix: update gdal version to 3.8.4 to fix footprints bug TDE-1106

---

scripts/stac/imagery/collection.py
scripts/stac/imagery/tests/collection_test.py

Add checksum to items links in collections to help with visibility at the collection level of when items are edited
Add checksum to items links in collections when the collection is being created 

feat: add checksum to item links in collections TDE-1138

---

scripts/dict_to_json_bytes.py
scripts/json_codec.py
scripts/stac/imagery/collection.py
scripts/standardise_validate.py

De-duplicate code. TBD: Determine whether we should `ensure_ascii=False` everywhere, based on [this discussion](https://linz.slack.com/archives/C01BWPHA1EU/p1635293737032700).
Centralise JSON encoding code.

refactor: Reuse dictionary to JSON bytes code TDE-1138

---

.github/workflows/format-tests.yml
README.md
scripts/standardise_validate.py
scripts/standardising.py

Give the user control of whether we create footprints for tiles. This is a workaround for some footprints resulting in unusably complex capture areas.
Add flag to control whether footprints (and therefore capture areas) are created.
We had to use a mandatory flag to workaround not finding how to [conditionally pass arguments with Argo Workflows](https://stackoverflow.com/q/78434236/96588).

feat!: add option to avoid creating footprints TDE-1159

---

CHANGELOG.md
pyproject.toml
scripts/files/fs.py
scripts/files/fs_local.py
scripts/files/fs_s3.py
scripts/files/tests/fs_local_test.py
scripts/files/tests/fs_s3_test.py
scripts/files/tests/fs_test.py
scripts/stac/imagery/item.py
scripts/stac/imagery/tests/collection_test.py
scripts/stac/imagery/tests/item_test.py

Give dataset users more detailed info about the datasets' life cycle.
Set item `created` and `updated` properties to current datetime when processing

feat: timestamps when created TDE-1147

---

scripts/stac/imagery/collection.py
scripts/stac/imagery/tests/generate_title_test.py

Align code with title naming convention documentation for [imagery](https://github.com/linz/imagery/blob/master/docs/naming.md#lifecycle) and [elevation](https://github.com/linz/elevation/blob/master/docs/naming.md#lifecycle)
Add `- Draft` to the end of a dataset title if the lifecycle status is `ongoing`

fix: add draft lifecycle tag TDE-1161

---

Dockerfile
scripts/docker-entrypoint.sh

Make build compatible with [GDAL 3.9 container](https://github.com/linz/topo-imagery/pull/962).
- Use multi-stage build to avoid including build tools in the final image.
- Install Poetry using pipx, as [recommended](https://python-poetry.org/docs/#installation).
- Use a different working directory in the first stage, to avoid the possibility of confusing the two or unintended interactions between them.
- Use a virtualenv to avoid clobbering OS packages.

fix: Make build compatible with new GDAL container TDE-1179

---

scripts/files/fs_s3.py
scripts/files/tests/fs_s3_test.py

Store checksum as s3 metadata so that we can determine if files have changed
- add checksum to s3 object [metadata](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/object/put.html#:~:text=S3%20on%20Outposts.-,Metadata%20(dict)%20%E2%80%93,(string)%20%E2%80%93,-ServerSideEncryption%20(string)) as `filechecksum`
nb: in the code, it is defined as `filechecksum` and in the tests you use `resp["Metadata"]["filechecksum"]` but something else adds the prefix `x-amz-meta-` here that I can't remove.

feat: add checksum metadata to s3 write function TDE-1181

---

Dockerfile
scripts/docker-entrypoint.sh

This reverts commit 719d96e1ff1133c351bbee7a1d93fa359cc702e4.
We are not using GDAL 3.9 and we had issues running the container within Argo Workflows since this change that modified how the Python environment is managed.
There are some jobs that need to be run on Argo workflows this week so we need to allow user to do it while we are finding a fix for the Argo issue.
_Why is this change being made? What implications or other considerations are there?_

revert: "fix: Make build compatible with new GDAL container TDE-1179 (#971)"

---

scripts/datetimes.py
scripts/stac/imagery/create_stac.py
scripts/stac/imagery/item.py
scripts/stac/imagery/tests/collection_test.py
scripts/stac/imagery/tests/item_test.py
scripts/tests/datetimes_test.py

When creating datasets, we want to set these to the current datetime.
Injects the function to get the current datetime, to allow testing the
exact values.

feat: Set created/updated item properties TDE-1147

---

scripts/collection_from_items.py
scripts/stac/imagery/collection.py
scripts/stac/imagery/tests/collection_test.py
scripts/stac/imagery/tests/generate_description_test.py
scripts/stac/imagery/tests/generate_title_test.py
scripts/stac/imagery/tests/item_test.py

These fields are not part of core STAC, and are not yet in the TTW LINZ extension. This has been relegated to a separate story <https://toitutewhenua.atlassian.net/browse/TDE-1192>.
Make it easier for end users to determine when a dataset was created/updated by providing these properties in the top level STAC document.

feat: Add created/updated properties to collections TDE-1147

---

scripts/aws/aws_credential_source.py
scripts/aws/aws_helper.py
scripts/cli/cli_helper.py
scripts/cli/tests/cli_helper_test.py
scripts/collection_from_items.py
scripts/files/file_tiff.py
scripts/files/fs.py
scripts/files/fs_s3.py
scripts/files/geotiff.py
scripts/files/tests/conftest.py
scripts/gdal/gdal_bands.py
scripts/gdal/gdal_helper.py
scripts/gdal/gdal_preset.py
scripts/gdal/gdalinfo.py
scripts/gdal/tests/gdalinfo.py
scripts/json_codec.py
scripts/stac/imagery/capture_area.py
scripts/stac/imagery/collection.py
scripts/stac/imagery/create_stac.py
scripts/stac/imagery/item.py
scripts/stac/imagery/metadata_constants.py
scripts/stac/imagery/provider.py
scripts/stac/imagery/tests/collection_test.py
scripts/stac/imagery/tests/generate_description_test.py
scripts/stac/imagery/tests/generate_title_test.py
scripts/standardise_validate.py
scripts/standardising.py
scripts/tile/tests/tile_index_data.py
scripts/tile/tile_index.py

Use post-Python 3.9 syntax for type annotations.
All N/A, just a type annotation change.

refactor: Simplify type annotations

---

scripts/files/geotiff.py
scripts/stac/imagery/collection.py
scripts/stac/imagery/create_stac.py
scripts/stac/imagery/item.py
scripts/stac/imagery/tests/collection_test.py
scripts/stac/imagery/tests/item_test.py
scripts/standardise_validate.py

The `update_*` methods were only there to make testing slightly more convenient, but also broke initialisation of the object into multiple stages. This way the production code is simpler (a single constructor invocation with no further initialisation), and the tests barely change to make sure all relevant properties are set.

refactor: Convert `ImageryItem` to a data class TDE-1147

---

scripts/stac/imagery/collection.py
scripts/stac/imagery/tests/collection_test.py

Fix runtime error in commands like `docker build -t topo-imagery . && docker run -v ${HOME}/tmp/:/tmp/:rw -v ${HOME}/.aws/credentials:/root/.aws/credentials:ro -e AWS_PROFILE=li-topo-prod topo-imagery python /app/scripts/collection_from_items.py --uri s3://linz-workflows-scratch/afage/small_example_dem_dataset/ --collection-id 01HYCJ3EXF37J4A9130AH7Q2RF --category dem --region hawkes-bay --gsd 1m --start-date 2023-09-20 --end-date 2023-12-21 --lifecycle ongoing --producer "Woolpert" --licensor "National Institute of Water and Atmospheric Research" --concurrency 25` on topo-prod account.
We load the item from a JSON file into a `dict` in the production code,
but none of our automated tests verify this code path, so it broke.
This partially reverts commit …

fix: Treat item as `dict` TDE-1209

---

scripts/files/geotiff.py
scripts/stac/imagery/collection.py
scripts/stac/imagery/create_stac.py
scripts/stac/imagery/item.py
scripts/stac/imagery/tests/collection_test.py
scripts/stac/imagery/tests/item_test.py
scripts/standardise_validate.py

Revert Pull Requests #993 and #985 
#985 caused [collection_from_item to fail](https://toitutewhenua.atlassian.net/browse/TDE-1209) and while #985 resolved that issue, it [creates invalid STAC Items](https://toitutewhenua.atlassian.net/browse/TDE-1217). Unit tests and GitHub Actions tests did not pick up these issues.
Revert commits 384d0fc674ce8fe4f1ff8726362881887a68522f and ed177c622dbb93587f00524635051c5f0f4a8b9f

revert: Pull Requests #993 and #985

---

scripts/files/fs.py
scripts/files/tests/fs_test.py

When supplying multiple source locations to use for standardising, if there are overlapping source images, the VRT created does not honour the priority order for the supplied datasets. This Pull Request is to retain the priority of the images for merging.
Move away from using `as_completed` for parallel processing so that the output file list is in the same order as the input file list.

fix: concurrency file order TDE-1213

---

Dockerfile

After a workstation upgrade of Docker CLI to v27, the [FromAsCasing build check](https://docs.docker.com/reference/build-checks/from-as-casing/) warning is logged
`=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)`
Use consistent case in the Dockerfile (from `as` to `AS`).
Built locally.

build: comply with Docker FromAsCasing build check

---

scripts/stac/imagery/capture_area.py
scripts/stac/imagery/tests/capture_area_test.py
scripts/stac/imagery/tests/collection_test.py

[An issue was raised on the Elevation repo](https://github.com/linz/elevation/issues/298) to let us know that the capture areas we are generating are not compliant with https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.6
Exterior polygon rings should follow the right-hand rule with a counter-clockwise winding order.
While the footprints generated by the standardising process are compliant with the right-hand rule, when the polygons are buffered for merging, [Shapely reverses the orientation of the polygons](https://github.com/shapely/shapely/issues/622).
Use the Shapely `orient` function to ensure that the capture area polygons have a counter-clockwise winding order.
[Example capture areas attached](https://github.com/user-attachments/files/16367933/examples.zip).
Unit tests to …

fix: capture area winding order TDE-1205

---

scripts/collection_from_items.py
scripts/tests/collection_from_items_test.py

Having automatic tests for `collection_from_items.py` script.
- Refactor `collection_from_items.py` `main()` function so it can be easily called passing a list of arguments.
- Add a simple test that verifies the `collection.json` file is created on a usual use case.
run `pytest`

test: init automatic tests for collection_from_items.py script TDE-1227

---

.github/workflows/containers.yml

It is useful to be able to publish a container from a PR code base so we can test the container using external environment such as Kubernetes.
- GH Actions workflow `containers.yml` will run when a `container` label is added to a PR. The container will only be published on the GH package repository and be tagged `pr-[PR-NUMBER]`
You can test it in this PR.
Also tested on a fork with the full process of merging the PR for non regression.

ci: publish container to gh on pr label container TDE-1252

---

scripts/stac/imagery/create_stac.py
scripts/stac/imagery/tests/create_stac_test.py

When a STAC Item is derived from other STAC Items, its `properties.start_datetime` and `properties.end_datetime` should be determined from the derived  items.
- list all the `start_datetime` and `end_datetime` of derived Items to determine the new Item start and end datetime.
tests

feat: determine start and end datetimes when item include derived TDE-1258

---

scripts/stac/imagery/tests/capture_area_test.py

Because the test were using `equals` they were checking that the shapes were equivalent, but not exactly the same (i.e. including the winding order). In fact [due to a change in orientation](https://toitutewhenua.atlassian.net/browse/TDE-1205), they were reversed, but `equals` does not check orientation.
This change is to reflect the correct data in order and use `equals_exact` to catch if this changes in future.
Use Shapely `Polygon.equals_exact()` instead of `Polygon.equals()` and update with the correct capture area test data.
pytest unit tests.

test: use equals_exact to check winding order of capture area

---

scripts/cli/cli_helper.py
scripts/standardise_validate.py

`start_datetime` and `end_datetime` should be optional in the case of the output tiles include derived items.
- make the input parameters not always required
Ran a couple of test workflows with the following:
- empty datetimes
- bad format datetime
- good format datetime

feat: make start_datetime and end_datetime optional when includeDerived is True TDE-1258

---

scripts/collection_from_items.py
scripts/stac/imagery/collection.py
scripts/stac/imagery/tests/collection_test.py

The [National 1m DEM dataset](https://toitutewhenua.atlassian.net/browse/TDE-1130) STAC collection will have an additional `capture-dates.geojson` asset that contains provenance information for the dataset.
Added an additional command line argument flag to `collection_from_items`: if `--capture-dates` is specified a `capture-dates.geojson` asset link (with checksum and file size) will be added to the STAC collection.
Example:
```    "assets": {
"capture_area": {
"href": "./capture-area.geojson",
"title": "Capture area",
"type": "application/geo+json",
"roles": [
"metadata"
],
"file:checksum": "1220e7357b15342abf53764861d20bbc7eed8a58bb662836bde9069dc8c68d247812",
"file:size": 576615
},
"capture_dates": {
"href": "./capture-dates.geojson.gz",
"title": "Capture dates",
"type": …
```

feat: add capture dates asset link to collection TDE-1256

---

.github/workflows/format-tests.yml

Avoids the following:
```
Installing the current project: […]
Warning: The current project could not be installed: No file/folder found for package […]
If you do not want to install the current project use --no-root.
If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
In a future version of Poetry this warning will become an error!
```
N/A

fix: Don't attempt to install project inside virtualenv

---

scripts/stac/imagery/collection.py
scripts/stac/imagery/create_stac.py
scripts/stac/imagery/item.py
scripts/stac/imagery/tests/collection_test.py
scripts/stac/imagery/tests/create_stac_test.py
scripts/stac/imagery/tests/item_test.py

https://github.com/radiantearth/stac-spec/blob/master/commons/links.md#stac-media-types
Change item links from media type `application/json` to `application/geo+json`.
`pytest`

fix: Use GeoJSON media type for item links TDE-1254

---

.github/workflows/format-tests.yml
CHANGELOG.md
README.md
poetry.lock
pyproject.toml
scripts/cli/cli_helper.py
scripts/collection_from_items.py
scripts/stac/imagery/capture_area.py
scripts/stac/imagery/collection.py
scripts/stac/imagery/create_stac.py
scripts/stac/imagery/item.py
scripts/stac/imagery/metadata_constants.py
scripts/stac/imagery/tests/capture_area_test.py
scripts/stac/imagery/tests/collection_test.py
scripts/stac/imagery/tests/create_stac_test.py
scripts/stac/imagery/tests/generate_description_test.py
scripts/stac/imagery/tests/generate_title_test.py
scripts/stac/imagery/tests/item_test.py
scripts/standardise_validate.py
scripts/standardising.py
scripts/tests/collection_from_items_test.py

This is always in metres, so we shouldn't ask the end user to fill it in.
Change GSD parameters to be decimal numbers, rather than strings
`pytest`

feat!: Auto-fill GSD unit TDE-1211

---

.github/workflows/format-tests.yml
Dockerfile
README.md
scripts/stac/imagery/create_stac.py
scripts/stac/imagery/item.py
scripts/stac/imagery/tests/collection_test.py
scripts/stac/imagery/tests/create_stac_test.py
scripts/stac/imagery/tests/item_test.py
scripts/stac/util/stac_extensions.py
scripts/standardise_validate.py
scripts/standardising.py
scripts/tests/collection_from_items_test.py

As a data maintainer, geospatial data engineer or data consumer, I would like to reference the technical configuration used to create the TIFFs in our ODR datasets in order to be able to recreate the TIFFs or carry out troubleshooting.
Add `processing:software`, `processing:version`, and `processing:datetime` item properties.
`pytest`

feat: Add topo-imagery version information to STAC TDE-1265

---

scripts/stac/imagery/tests/collection_test.py
scripts/stac/imagery/tests/conftest.py
scripts/stac/imagery/tests/generate_description_test.py
scripts/stac/imagery/tests/generate_title_test.py

The collection metadata used for testing is duplicated in the code base which makes it difficult to maintain.
Use the same collection metadata for all the related tests.
ran pytest

test: refactor fake collection metadata

---

scripts/stac/imagery/collection.py
scripts/stac/imagery/provider.py
scripts/stac/imagery/tests/collection_test.py

When a user add the same provider (same `name`) as a different role (for example, `--licensor='Maxar' --producer='Maxar'`) the provider should not be duplicated, but added with both role (for example: `{'name': 'Maxar', 'roles': ['producer', 'licensor']}`).
- merge provider list based on their name
- sort provider roles alphabetically (for readibility and conveniance) when added to the Collection
automatic tests

fix: providers should not be duplicated when having different roles TDE-1286

---

scripts/collection_from_items.py
scripts/stac/imagery/collection.py
scripts/stac/imagery/create_stac.py
scripts/stac/imagery/tests/generate_title_test.py

Some datasets might not required a suffix in their title. For example, a dataset with an `ongoing` lifecycle could not be tagged as a ` - Draft`.
- add an optional parameter `--add-title-suffix` (defaulted `True`) to the `collection_from_items.py` script so the title suffix, for example ` - Draft` can be ommitted in any case
automatic tests

feat: allow forcing Collection title to not have suffix TDE-1289

---

scripts/stac/imagery/collection.py
scripts/stac/imagery/tests/collection_test.py

To show a data consumer more information about what kind of data the linked `capture-area.geojson` and `capture-dates.geojson` files hold without having to view those.
Added a `description` field to the `capture_area` and `capture_dates` Asset objects created in `collection.py` and associated tests.
Unit tests updated to include the new data fields.
pre-commit checks to unify formatting.

feat: add description field for assets in collection TDE-1294

---

scripts/docker-entrypoint.sh
scripts/gdal/gdal_helper.py
scripts/standardise_validate.py

Simplify getting the gdal version.
Use system environment variable to store the gdal version value rather than calling the shell from Python.
Ran E2E test

refactor: use environment variable to get GDAL version

---

scripts/stac/imagery/create_stac.py
scripts/stac/imagery/item.py
scripts/stac/imagery/tests/collection_test.py
scripts/stac/imagery/tests/generators.py
scripts/stac/imagery/tests/item_test.py
scripts/tests/collection_from_items_test.py
scripts/tests/datetimes_test.py

Pull out STAC asset and processing data types.
Modified unit tests accordingly.

refactor: Simplify `ImageryItem` constructor TDE-1298

---

scripts/stac/imagery/capture_area.py
scripts/stac/imagery/tests/collection_test.py

Caveat: Shapely's `BaseGeometry.buffer` produces different results on different machines, even with exactly the same Python package versions installed. To reproduce, change `test_should_make_valid_capture_area` to run with a buffer distance of `0.3`, and revert the change in `merge_polygons`. At this point the test passes on my machine, but fails on @schmidtnz's machine! We tracked this down to the line `union_buffered.buffer(-buffer_distance, cap_style=BufferCapStyle.flat, join_style=BufferJoinStyle.mitre)`. With the changes mentioned above, this returns a `MultiPolygon` on my machine (basically doing the same as `make_valid`, and therefore making the test pass), and a `Polygon` on @schmidtnz's machine (making the `make_valid` necessary to produce a valid polygon).
Ensure that published …

fix: Make capture area geometry valid TDE-1306

---

scripts/stac/imagery/tests/collection_test.py

Refactoring to support TDE-1298 - handle subtests for all created and updated dates in a similar manner
Changed `test_add_item` to include `assets.visual` `updated` and `created` attributes in `for` loop.
`pytest`

refactor: assert asset create and update times in loop TDE-1298

---

scripts/stac/imagery/item.py
scripts/stac/link.py
scripts/stac/util/media_type.py

Refactoring to support TDE-1298 - only allow one link of each of the types `Collection`, `Parent`, `Self`.
Added logic in `ImageryItem`s `add_link` method to recognise when a link of each type already exists.
Added `__str__` method to `StacMediaType` and `Relation` types, and made sure the `Link` class will contain strings for `rel` and `type`.
`pytest`

refactor: only allow one of specific link types TDE-1298

---

scripts/stac/imagery/create_stac.py

Rearrange function flow in `create_stac.py` to simplify implementation of TDE-1298.
Changed which function outputs would be kept in a local variable and moved creating `stac_asset` closer to where it is used.
`pytest`

refactor: rearranged create_stac.py to support TDE-1298

---

scripts/aws/aws_helper.py
scripts/aws/tests/aws_helper_test.py
scripts/collection_from_items.py
scripts/files/fs.py
scripts/files/fs_s3.py
scripts/files/tests/fs_s3_test.py
scripts/files/tests/fs_test.py
scripts/gdal/gdal_helper.py
scripts/stac/imagery/tests/collection_test.py
scripts/tests/collection_from_items_test.py

The latter is deprecated
<https://boto3.amazonaws.com/v1/documentation/api/1.35.60/guide/resources.html>.
- Use the lower-level clients API instead of resources.
- Type annotate S3 clients to make IDE use easier.
Standard tests.

refactor: Use boto3 clients rather than resources TDE-1034

---

scripts/collection_from_items.py
scripts/datetimes.py
scripts/files/fs.py
scripts/files/fs_local.py
scripts/files/fs_s3.py
scripts/files/tests/fs_local_test.py
scripts/files/tests/fs_s3_test.py
scripts/files/tests/fs_test.py
scripts/stac/imagery/collection.py
scripts/stac/imagery/create_stac.py
scripts/stac/imagery/tests/collection_test.py
scripts/stac/imagery/tests/create_stac_test.py
scripts/stac/imagery/tests/generate_description_test.py
scripts/stac/imagery/tests/generate_title_test.py
scripts/stac/imagery/tests/item_test.py
scripts/tests/collection_from_items_test.py

Ensure that the STAC Collection `properties.created` datetime is not changed when resupplying.
- Add `--published-path` parameter to `collection_from_items.py`, to get created datetime on resupply.
- Add `--current-datetime` parameter to `collection_from_items.py` to use that instead of the actual clock time for created/updated datetimes.

feat: keep Collection properties.created date when resupplying

---

scripts/standardise_validate.py

As a basemaps developer, I do not want to set many mandatory CLI arguments.
Added the current date / time as a semi-sane default for the `--current-date` command line argument
`pytest`

feat: defaults for current-datetime argument TDE-1298

---

scripts/aws/aws_helper.py

Missing update from #1172.
Untested

fix: Use client syntax for getting file contents

---

scripts/collection_from_items.py
scripts/tests/collection_from_items_test.py

As a basemaps developer, I do not want to set many mandatory CLI arguments.
Added the current date / time as a semi-sane default for the --current-date command line argument
pytest

feat: set default current-date for collection_from_items script TDE-1298

---

scripts/stac/imagery/create_stac.py
scripts/stac/imagery/tests/create_stac_test.py
scripts/tests/data/fake_item.json

When a published Item with `derived_from` links is resupplied, its existing list of `derived_from` links may have changed with the resupply. The current implementation would duplicate existing `derived_from` links and left obsolete ones. It will also remove any `derived_from` links in case of the Item is not derived from other Items anymore.
Remove existing `derived_from` links to the STAC Item before processing the current `derived_from` links list.
Pytest
Argo Workflows

fix: handle existing derived_from links when Item is updated TDE-1356

---

scripts/stac/imagery/item.py

Renaming variable for readibility as the data to create the stac item from a file is not always coming from an s3 location.
- Rename `stac_dict_from_s3` to `stac_from_file`

refactor: rename stac dict variable in ImageryItem.from_file()

---

scripts/files/file_tiff.py
scripts/gdal/gdal_commands.py
scripts/gdal/gdal_presets.py
scripts/gdal/tests/gdal_commands_test.py
scripts/standardising.py
scripts/thumbnails.py
scripts/translate_ascii.py

`gdal_preset.py` was handling GDAL command generation built of "presets". It is confusing having a `gdal_preset.py` and a `gdal_presets.py` file.
- Rename `gdal_preset.py` -> `gdal_commands.py` for the script file that manages the GDAL command generation
- Move the "preset" definitions to `gdal_presets.py` file

refactor: re-organize gdal presets

---

.github/workflows/format-tests.yml

Github is deprecating v3 of the artifact actions.
Update version of upload-artifact to current latest version number 4.6.0
Ran action without the `if: failure()` condition and it successfully uploaded all artifacts.

fix: deprecated artifact action TDE-1379

---

scripts/gdal/gdal_commands.py
scripts/standardise_validate.py
scripts/standardising.py

To generate a national combined hillshade product, we need to be able to combine inputs of differing resolutions and ensure consistent output.
The default settings of `gdalbuildvrt` will average all input resolutions. This change implements a more suitable setting for our use-case.
Add optional `resolution` argument to  `get_build_vrt_command()`, which will in turn add `-resolution user -tr <xres> <yres>` arguments to the respective GDAL command.
`standardising()` now accepts a list `scale_to_resolution = [x_res, y_res]` to support the above.
Manual test run with combined DEM hillshades.

feat: add resolution argument to gdalbuildvrt TDE-1383

---

scripts/stac/imagery/collection.py
scripts/stac/imagery/metadata_constants.py
scripts/stac/imagery/tests/collection_test.py

In order to generate a national hillshade product, we need suitable titles and descriptions for these datasets.
* Implement tests for new DEM hillshade descriptions and titles.
* Add suitable constants to metadata_constants.py
* Update collection.py `ImageryCollection()` `_title()` and `_description()` methods to support two new DEM hillshade types.
* Refactor changed methods in collection.py for consistency and flow.
Newly implemented unit tests.

feat: titles and descriptions for hillshade products TDE-1378

---

scripts/standardising.py

If user pass argument `--cutline=''` the standardising_validate script should not raise an error and should avoid the cutline value.
- fix bug

fix: should not raise error when cutline is empty TDE-1392

---

scripts/cli/cli_helper.py
scripts/cli/tests/cli_helper_test.py

Argo Workflows supplies single quotes for optional parameters, which are not valid dates. These are handled later in the `standardise_validate.py` code.
Allow an empty string to be accepted by the command line parser for the start and end dates.
Added unit tests. Tested from Argo Workflows using a PR container.

fix(standardise-validate): allow empty string from Argo for start and end dates TDE-1346

---

scripts/stac/imagery/capture_area.py
scripts/stac/imagery/tests/capture_area_test.py
scripts/stac/imagery/tests/collection_test.py

When an existing capture-area geometry is being modified (polygon being removed/added), as a result the polygons points can be moved around. When the overall geometry ends up being the same (no visual change), we prefer the capture-area geometry to not show a change (difference between existing and new/re-processed one).
- Use [shapely.normalize()](https://shapely.readthedocs.io/en/2.0.3/reference/shapely.normalize.html) to keep the geometry consistent.
What does `shapely.normalize()`?
According to [the official documentation](https://shapely.readthedocs.io/en/latest/geometry.html#canonical-form):
> - the coordinates of exterior rings follow a clockwise orientation and interior rings have a counter-clockwise orientation
> - the starting point of rings is lower left
> - elements in …

feat: normalize capture-area geometry TDE-1359

---

scripts/stac/imagery/capture_area.py
scripts/stac/imagery/tests/capture_area_test.py
scripts/stac/imagery/tests/collection_test.py

This reverts commit 0a061ba3910a2ed60aecf8b9ad1ec5ebc5cf80df.
Normalizing as it has been implemented brings some issues into the overall geometry (visual and QGIS artifacts). As discussed and decided, having the capture-area content being different (points ordering) that shows a difference when updating an existing dataset while its geometry is not visually changed should not be a big deal for data consumer.
- Revert https://github.com/linz/topo-imagery/pull/1288
None

revert: normalize capture-area geometry TDE-1359 (#1288) TDE-1423

---

scripts/cli/cli_helper.py
scripts/collection_from_items.py
scripts/standardise_validate.py

Argo Workflows supplies single quotes where parameters are not supplied, which can happen if a workflow template is used by multiple workflows. This breaks optional parameters in argparse.
Convert Argo string to boolean to control adding the capture dates file and the title suffix, in line with how the capture area creation (footprint) is handled.
Ran workflow in Argo and locally on the command line.

fix: handle optional flags from Argo TDE-1346

---

scripts/stac/imagery/collection.py
scripts/stac/imagery/tests/collection_test.py

When updating an existing Collection, its extents has to be reset in order to be recalculated from the new list of Items.
- Allow to reset the Collection extents without removing its dictionnary entry to avoid potential change in the Collection dictionnary structure/order
- Refactor `update_extent()` for simplification
Run unit tests

feat: reset Collection extents TDE-1359

---

.github/workflows/format-tests.yml
scripts/gdal/gdal_commands.py
scripts/gdal/gdal_presets.py

Update `HillshadePreset` values to match use throughout the workflow and remaining code.
`GREYSCALE = "greyscale"` -> `DEFAULT = "hillshade"`
`IGOR = "igor"` -> `IGOR = "hillshade-igor"`
existing `pytest` tests and github actions end to end tests.

fix: update hillshade preset enum values TDE-1371

---

scripts/stac/imagery/tests/collection_test.py

`test_should_not_add_capture_area()` docstring has been copy-pasted from another test and does not reflect what the test is intended to do.
Update the docstring of `test_should_not_add_capture_area()` accordingly to what the test is verifying.

docs: update test_should_not_add_capture_area comment

---

scripts/collection_from_items.py
scripts/stac/imagery/collection.py
scripts/stac/imagery/metadata_constants.py
scripts/stac/imagery/tests/collection_test.py
scripts/stac/imagery/tests/conftest.py
scripts/stac/imagery/tests/generate_description_test.py
scripts/stac/imagery/tests/generate_title_test.py
scripts/stac/imagery/tests/item_test.py
scripts/tests/collection_from_items_test.py

Using a `dataclass` gives advantages such as type safety at runtime, attributes access vs dictionary lookups, supports default values, IDE hints are better, etc.
- Convert `CollectionMetadata` from a `TypedDict` to a `dataclass`
The caveat is that the linter complains about too many instance attributes.
I've thought about splitting it up into few other dataclass, but it makes it more readable and maintainable.
Automatic tests

refactor: make CollectionMetadata a dataclass TDE-1443

---

scripts/collection_from_items.py
scripts/stac/imagery/collection.py
scripts/stac/imagery/create_stac.py

Avoiding hardcoded value when used in several places makes the code cleaner and more maintainable: easy to update, reduce errors, etc.
- Centralize `collection.json` Collection file name in one place

refactor: use constant for Collection file name

---

scripts/collection_from_items.py
scripts/conftest.py
scripts/stac/imagery/collection.py
scripts/stac/imagery/create_stac.py
scripts/stac/imagery/metadata_constants.py
scripts/stac/imagery/tests/collection_test.py
scripts/stac/imagery/tests/conftest.py
scripts/stac/imagery/tests/create_stac_test.py
scripts/stac/imagery/tests/generate_description_test.py
scripts/stac/imagery/tests/generate_title_test.py
scripts/stac/imagery/tests/item_test.py
scripts/tests/collection_from_items_test.py

`create_collection()` has too many arguments and it is difficult to manage them. While having the need of adding even more arguments in the near future, this change is needed.
- Group Collection identifiers `linz_slug` and `id` into the same dataclass
- Group creation options `add_capture_dates` and `add_title_suffix` into the same dataclass
linter, typer, and UTs

refactor: group arguments used to create Collection TDE-1443

---

scripts/stac/imagery/collection.py
scripts/stac/imagery/create_stac.py
scripts/stac/imagery/tests/collection_test.py

`ImageryCollection.from_file()` should only handle loading the STAC metadata from the existing Collection file and not doing any other logic.
- Move extra logic where loading the collection is called from.
Automated tests

refactor: `ImageryCollection.from_file()` only handles loading the STAC metadata TDE-1443

---

scripts/generate_hillshade.py

When generating hillshade TIFF and Items, the system may need to retrieve the already published tiles in order to properly update them rather than re-creating the entire metadata.
- Add missing argument `--odr-url` to the `generate_hillshade.py` script
- TODO: topo-workflow modification
Manual testing

fix: allow to pass ODR URL to `generate_hillshade.py` TDE-1452

---

scripts/stac/imagery/tests/collection_test.py

When running `pytest`, the `parametrized` tests output is difficult to read. For example:
```shell
scripts/stac/imagery/tests/collection_test.py::test_hillshade_title_and_description[dem-hillshade-gsd0-New Zealand 8m DEM Hillshade-Hillshade generated from the New Zealand Contour-Derived 8m DEM using GDAL\u2019s default hillshading parameters of 315\u02da azimuth and 45\u02da elevation angle.] [8m DEM Hillshade Title] SUBPASS [  7%]
scripts/stac/imagery/tests/collection_test.py::test_hillshade_title_and_description[dem-hillshade-gsd0-New Zealand 8m DEM Hillshade-Hillshade generated from the New Zealand Contour-Derived 8m DEM using GDAL\u2019s default hillshading parameters of 315\u02da azimuth and 45\u02da elevation angle.] [8m DEM Hillshade Description] SUBPASS [  7%] …
```

refactor: improve pytest parametrized tests output TDE-1464

---

scripts/stac/imagery/collection_context.py
scripts/stac/imagery/constants.py
scripts/stac/imagery/tests/collection_test.py

As a Basemaps user
I want national DSM hillshades (1m and unspecified resolution, standard and igor)
So that I can view/accentuate terrain detail in a variety of basemaps.
- add description/title templates for DSM hillshades in collection context
- add test cases for DSM hillshades
- add constants for DSM hillshades
Added tests, run workflows using PR container

feat: support national DSM hillshades TDE-1455

---

scripts/stac/imagery/tests/collection_test.py

`test_set_title_set_description()` automated test can be re-use with the hillshade parameters so we don't duplicate the test function.
- refactor the hillshade title and description tests parameters to merge them in the `test_set_title_set_description()` parameters.
run pytest

test: merging hillshade title and description tests into test_set_title_set_description()

---

scripts/stac/imagery/create_stac.py
scripts/stac/imagery/tests/create_stac_test.py

When there is no odr url provided, the title can't be "keep" as there is no existing Collection for this dataset.
- set collection title when there is no odr url even if keep-title is True
Automated test
Argo Workflows

fix: Collection title should always be set when no odr url is provided TDE-1539

---

scripts/collection_from_items.py
scripts/conftest.py
scripts/stac/imagery/collection.py
scripts/stac/imagery/collection_context.py
scripts/stac/imagery/constants.py
scripts/stac/imagery/tests/collection_test.py
scripts/tests/collection_from_items_test.py

Some datasets share the same category (for example, "DEM") but diverge on their domain such as the Coastal datasets.
- add a dataset domain to handle Collection Title and Description. Default domain is "Land" and is not visible in the generated data.
See https://github.com/linz/elevation/pull/420
Automated tests
Argo Workflows

feat: add dataset domain TDE-1542

---

scripts/collection_from_items.py
scripts/stac/imagery/collection_context.py
scripts/stac/imagery/create_stac.py
scripts/stac/imagery/tests/create_stac_test.py

:mega: **Note:** this is linked to https://github.com/linz/topo-workflows/pull/1052 which will use this flag.
The DEM merged hillshades need a custom description in the same way that some datasets need a custom title. Add an option to keep existing descriptions (load them from the ODR URL).
Added a new flag `--keep-description` when updating the collection for the merged hillshades.
Unit tests and tested with a workflow. The collection was created with the existing description.

feat: keep existing collection description TDE-1498

---

.github/workflows/containers.yml
.github/workflows/release-please.yml

Stop using `GITHUB_TOKEN` for release-please.

ci: stop using GITHUB_TOKEN for release-please TDE-1584

---

scripts/stac/imagery/capture_area.py
scripts/stac/imagery/tests/capture_area_test.py
scripts/stac/imagery/tests/collection_test.py

When working on https://toitutewhenua.atlassian.net/browse/TDE-1604 the capture area generated did not follow the right hand rule. If the `make_valid` step is removed, the orientation is correct.
Do the `make_valid` step before forcing the orientation to follow the right hand winding order rule. I did contemplate an `is_valid` check but `orient` should not make the geometry invalid.
Unit tests and a manual test with the larger capture area that had been reversed.

fix: orient the capture area after making geometry valid TDE-1618

---

scripts/cli/cli_helper.py
scripts/cli/tests/cli_helper_test.py
scripts/collection_from_items.py
scripts/stac/imagery/collection.py
scripts/stac/imagery/create_stac.py
scripts/stac/imagery/tests/capture_area_test.py
scripts/stac/imagery/tests/collection_test.py
scripts/standardise_validate.py

For 3D Coastal mapping datasets the capture areas automatically generated when standardising are very complex. This change is to allow a simpler capture area to be added when creating a collection rather than calculating it from the TIFF footprints.
Added a new parameter `supplied_capture_area` to be used by the `create-collection` step.
Unit tests.
Ran workflows manually against topo-imagery PR container.

feat: use supplied capture area TDE-1604

---

scripts/stac/imagery/collection.py

`aerial-photos` is a category available in our argo workflows, but the standardising workflow fails to create STAC when selected.
Add `AERIAL_PHOTOS` as a valid category in addition to `URBAN_AERIAL_PHOTOS, RURAL_AERIAL_PHOTOS`.
manual workflow run

fix: accept aerial-photos as a category TDE-1650

---

scripts/stac/imagery/collection.py
scripts/stac/imagery/tests/collection_test.py

As an imagery maintainer
I want to make sure the GSD values across a survey is consistent in all TIFF images
so that the data is consistent and accurate (in line with the metadata)
GSD value of the associated assets needs to be saved in the `collection.json` file for easy access when validating GSD in stac-setup.
Added `gsd` metadata to our STAC collection.
added unit tests.

feat: add GSD metadata to collection.json TDE-1657
